module.exports = {
  value: [
    '<sub alias="あかだま">赤玉</sub>',
    '<sub alias="あくだま">悪玉</sub>',
    '揚げ玉',
    '<sub alias="あしだま">足玉</sub>',
    '<sub alias="あじたま">味玉</sub>',
    '<sub alias="あぶらだま">油玉</sub>',
    '<sub alias="あめだま">飴玉</sub>',
    'あんこ玉',
    '<sub alias="いちえんだま">一円玉</sub>',
    '<sub alias="いのちだま">命玉</sub>',
    '<sub alias="うきだま">浮き玉</sub>',
    '牛の玉',
    '<sub alias="うすだま">臼玉</sub>',
    '<sub alias="うなたま">鰻玉</sub>',
    '<sub alias="うばたま">烏羽玉</sub>',
    '<sub alias="おおだま">大玉</sub>',
    '<sub alias="おおめだま">大目玉</sub>',
    'おたま',
    'お手玉',
    'お目玉',
    '<sub alias="おやだま">親玉</sub>',
    '<sub alias="おんたま">温玉</sub>',
    '替え玉',
    '<sub alias="かえんだま">火焔玉</sub>',
    '<sub alias="かきたま">掻き玉</sub>',
    '<sub alias="かくしだま">隠し球</sub>',
    '<sub alias="かにたま">蟹玉</sub>',
    '<sub alias="からふとだま">樺太玉</sub>',
    '<sub alias="がんぎだま">雁木玉</sub>',
    '<sub alias="かんしゃくだま">癇癪玉</sub>',
    '肝っ玉',
    '<sub alias="きめだま">決め球</sub>',
    '<sub alias="ぎゃくたま">逆玉</sub>',
    '<sub alias="きりこだま">切子玉</sub>',
    '<sub alias="ぎんだま">銀玉</sub>',
    '<sub alias="くすだま">薬玉</sub>',
    '<sub alias="くせだま">曲玉</sub>',
    '<sub alias="くびったま">首っ玉</sub>',
    '<sub alias="くろだま">黒玉</sub>',
    '<sub alias="けだま">毛玉</sub>',
    'けん玉',
    '<sub alias="ごえんだま">五円玉</sub>',
    '<sub alias="ごじゅうえんだま">五十円玉</sub>',
    '<sub alias="こだま">木霊</sub>',
    '<sub alias="ごひゃくえんだま">五百円玉</sub>',
    '<sub alias="こぼれだま">こぼれ球</sub>',
    '<sub alias="こんにゃくだま">蒟蒻玉</sub>',
    '<sub alias="さいたま">埼玉</sub>',
    '<sub alias="さきたま">埼玉</sub>',
    '<sub alias="さそいだま">誘い球</sub>',
    'シャボン玉',
    '<sub alias="じゅうえんだま">十円玉</sub>',
    '<sub alias="じょうだま">上玉</sub>',
    '<sub alias="しょうぶだま">勝負球</sub>',
    '<sub alias="しらたま">白玉</sub>',
    '<sub alias="ぜんだま">善玉</sub>',
    '<sub alias="つりだま">釣り球</sub>',
    '<sub alias="てだま">手玉</sub>',
    '<sub alias="でだま">出玉</sub>',
    '<sub alias="てっぽうだま">鉄砲玉</sub>',
    'とんぼ玉',
    '<sub alias="ながれだま">流れ弾</sub>',
    '<sub alias="なんきんだま">南京玉</sub>',
    '<sub alias="においだま">匂い玉</sub>',
    '<sub alias="にらたま">ニラ玉</sub>',
    'ビー玉',
    '火の玉',
    '<sub alias="ひゃくえんだま">百円玉</sub>',
    '<sub alias="ひょうろくだま">兵六玉</sub>',
    '<sub alias="ふきだま">吹玉</sub>',
    '<sub alias="ほうじゅのたま">宝珠の玉</sub>',
    '<sub alias="まがたま">勾玉</sub>',
    '<sub alias="まとだま">的玉</sub>',
    '<sub alias="まゆだま">繭玉</sub>',
    '<sub alias="みずたま">水玉</sub>',
    '<sub alias="みそだま">味噌玉</sub>',
    '<sub alias="みせだま">見せ球</sub>',
    '<sub alias="みみだま">耳玉</sub>',
    '<sub alias="むだだま">無駄球</sub>',
    '<sub alias="めだま">目玉</sub>',
    '<sub alias="やりだま">槍玉</sub>',
    '竜の玉',
  ],
};
